name: build-and-release
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22 # This is the crucial fix for the 'ERR_INVALID_ARG_TYPE'

      - name: Build Site
        run: |
          npm install @osmoscraft/osmosfeed
          npx @osmoscraft/osmosfeed build
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Matches your log's output folder
